/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as handleProxyForLensProtocolSol from "./HandleProxyForLensProtocol.sol";
export { HandleProxyForDID__factory } from "./HandleProxyForDID__factory";
export { IHandleProxy__factory } from "./IHandleProxy__factory";
