/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DID__factory } from "./DID__factory";
export { DIDResolver__factory } from "./DIDResolver__factory";
export { IDIDResolver__factory } from "./IDIDResolver__factory";
export { Metadata__factory } from "./Metadata__factory";
export { Price__factory } from "./Price__factory";
