/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoTaskMainSol from "./DAOTaskMain.sol";
export type { daoTaskMainSol };
export type { DAOTaskOrder } from "./DAOTaskOrder";
export type { DAOTaskOrderNFT } from "./DAOTaskOrderNFT";
export type { POAP } from "./POAP";
