/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIdeaSBT } from "./IIdeaSBT";
export type { IdeaNFT } from "./IdeaNFT";
export type { IdeaSBT } from "./IdeaSBT";
