/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxy from "./proxy";
export { IIdeaSBT__factory } from "./IIdeaSBT__factory";
export { IdeaDID__factory } from "./IdeaDID__factory";
export { IdeaSBT__factory } from "./IdeaSBT__factory";
export { SubIdeaSBT__factory } from "./SubIdeaSBT__factory";
