/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as idea3 from "./idea3";
export type { idea3 };
