/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxy from "./proxy";
export type { proxy };
export type { IIdeaSBT } from "./IIdeaSBT";
export type { IdeaDID } from "./IdeaDID";
export type { IdeaSBT } from "./IdeaSBT";
export type { SubIdeaSBT } from "./SubIdeaSBT";
