/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ownableSol from "./ownable.sol";
export type { ownableSol };
export type { MockERC20 } from "./MockERC20";
